cc_library(
    name = "Bullet3Common",
    srcs = glob([
            "src/Bullet3Common/*.cpp",
            "src/Bullet3Common/shared/*.cpp"
        ]),
    hdrs = glob([
                "src/Bullet3Common/*.h",
                "src/Bullet3Common/shared/*.h"
            ]),
    includes = ["src"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Bullet3Collision",
    srcs = glob([
            "src/Bullet3Collision/NarrowPhaseCollision/*.cpp",
            "src/Bullet3Collision/NarrowPhaseCollision/shared/*.cpp",
            "src/Bullet3Collision/BroadPhaseCollision/*.cpp",
            "src/Bullet3Collision/BroadPhaseCollision/shared/*.cpp"
        ]),
    hdrs = glob([
            "src/Bullet3Collision/NarrowPhaseCollision/*.h",
            "src/Bullet3Collision/NarrowPhaseCollision/shared/*.h",
            "src/Bullet3Collision/BroadPhaseCollision/*.h",
            "src/Bullet3Collision/BroadPhaseCollision/shared/*.h"
        ]),
    deps = [
        ":Bullet3Common",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Bullet3Dynamic",
    srcs = glob([
            "src/Bullet3Dynamic/*.cpp",
            "src/Bullet3Dynamic/shared/*.cpp",
            "src/Bullet3Dynamic/ConstraintSolver/*.cpp",
        ]),
    hdrs = glob([
            "src/Bullet3Dynamic/*.h",
            "src/Bullet3Dynamic/shared/*.h",
            "src/Bullet3Dynamic/ConstraintSolver/*.h",
        ]),
    deps = [
        ":Bullet3Common",
        ":Bullet3Collision",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Bullet3Geometry",
    srcs = glob([
            "src/Bullet3Geometry/*.cpp",
        ]),
    hdrs = glob([
            "src/Bullet3Geometry/*.h",
        ]),
    deps = [
        ":Bullet3Common",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Bullet3Serialize",
    srcs = glob([
            "src/Bullet3Serialize/Bullet2FileLoader/*.cpp",
        ]),
    hdrs = glob([
            "src/Bullet3Serialize/Bullet2FileLoader/*.h",
            "src/Bullet3Serialize/Bullet2FileLoader/autogenerated/*.h",
        ]),
    deps = [
        ":Bullet3Common",
    ],
    visibility = ["//visibility:public"],
)
