THIS_DIR1=./
THIS_DIR2=./
DEL_CMD=rm -f
CC=g++
OBJ=.o
C_FLAGS=-c -Wall -fno-rtti -fno-exceptions -Wall -I/usr/X11R6/include
C_INC=-I
C_OUT=-o 
C_EXEOUT=-o 
C_DEF=-D
C_OPT=-O
AR=ar rc 
RANLIB=ranlib -s
LIB_PREFIX=lib
LIB_SUFFIX=.a
LINK_OPENGL=-L/usr/X11R6/lib -lX11 -lGL -lGLU
LINK_MATH=-lm

ifeq ($(BUILD),release)
OPT=2
C_FLAGS+=-fomit-frame-pointer -ffast-math
endif

ifeq ($(BUILD),debug)
OPT=0
C_FLAGS+=-g
endif

I_AM_GCC=yes


