#ifndef GENERIC_6DOF_SPRING2_CONSTRAINT_TUTORIAL_H
#define GENERIC_6DOF_SPRING2_CONSTRAINT_TUTORIAL_H

class CommonExampleInterface* Dof6ConstraintTutorialCreateFunc(struct CommonExampleOptions& options);

#endif  //GENERIC_6DOF_SPRING2_CONSTRAINT_TUTORIAL_H
