#### Visit Bullet library ibmsdk dirs and build  code
CELL_TOP ?= ../..

DIRS :=					\
../BulletCollision/ibmsdk		\
../BulletDynamics/ibmsdk		\
../LinearMath/ibmsdk


include $(CELL_TOP)/make.footer
